apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: kube-app
  name: kube-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      run: kube-app
  template:
    metadata:
      labels:
        run: kube-app
    spec:
      containers:
      - name: kube-app
        image: kube-app
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        volumeMounts:
        - name: appsettings-volume
          mountPath: /app/set
      volumes:
      - name: appsettings-volume
        configMap:
          name: appsettings